server:
  port: 8899

spring:
  datasource:
    url: jdbc:mysql://119.45.45.55:3306/crud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: 519nbao@HHU
    driver-class-name: com.mysql.cj.jdbc.Driver